MODEL:
  META_ARCHITECTURE: "Student"
  DEVICE: "cuda"
INPUT:
  FORMAT: "BGR"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 720
DATASETS:
  TRAIN: ("coco_2017_sem_train",)
  TEST: ("coco_2017_sem_val",)
  NUM_CLASSES: 81
DATALOADER:
  NUM_WORKERS: 0
  ASPECT_RATIO_GROUPING: True
  SAMPLER_TRAIN: "TrainingSampler"
  FILTER_EMPTY_ANNOTATIONS: True
SOLVER:
  BASE_LR: 0.001
  IMS_PER_BATCH: 8
  MAX_ITER: 443580         # 29572 * 30
  CHECKPOINT_PERIOD: 14786 # ceil(118287 / 8)
TEST:
  EVAL_PERIOD: 14786
OUTPUT_DIR: "./output/Student_pretrain"
VERSION: 2
